logging:
  config: classpath:logback.xml
  level:
    com:
      example:
        websocket: debug
  path: ./target/logs
server:
  port: 9970
weblogPath: ${logging.path}\spring.log

spring:
  datasource:
    url: jdbc:mysql://134.175.34.61:3306/websocket?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: websocket
    password: wNAeXs2TmW8MnAfC


